name: osfjaarverslag2022
baseurl:
host: 0.0.0.0
gems: ['jekyll/minibundle']
title: >
  Open State Foundation jaarverslag 2022
description: >
  open data, transparante samenleving
production_url: https://2022.openstate.eu
